print("enter the value for a:")
a=int(input())
print("enter the value for b:")
b=int(input())
print("enter the value for c:")
c=int(input())
if (a>b) and (a>c):  print(a,"is the greatest")
if (b>a) and (b>c):  print(b,"is the greatest")
if (c>b) and (c>a):  print(c,"is the greatest")
